# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

#gems

gems: [jekyll-paginate, jekyll-gist]

paginate: 3 

# Setup
title:            Alex Beaulieu
tagline:          'Web Developer'
description:      'Front End Web Developer. Technology communicator. Curious Human.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde





